
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-02-08T09:12:57-0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "d25e0bae284b776820ae70cde91339e6cab3c62d",
 "version": "0+untagged.45.gd25e0ba.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
